name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install composer dependencies
        run: composer install --prefer-dist

      - name: PHPInsights
        run: composer phpinsights

      - name: PHP-CS-Fixer
        run: composer cs:check

      - name: Laravel PHPUnit
        run: composer test

